"""The mesh boundary — patch names and types (FR-P4).

``constant/polyMesh/boundary`` is what the boundary-condition matrix is built
from: its rows are the patches this file declares, and its patch *types* decide
which boundary conditions are legal in each cell (E-C04).

The file is generated by ``blockMesh`` or ``snappyHexMesh``, never edited by
hand, so this reader is deliberately read-only. Writing boundary conditions
happens in the field files under ``0/``, which are ordinary dictionaries the
round-trip machinery already handles.

It is stored in OpenFOAM's counted-list form, which the structural parser keeps
opaque because a list is not a set of editable entries. The interior, however, is
exactly a dictionary body — ``name { type wall; ... }`` repeated — so it is
extracted and parsed with the same parser rather than with a second, differently
buggy one.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path

from foamwb.services.foamdict import Document, NodeKind, ParseError

__all__ = ["BOUNDARY_FILE", "Patch", "PatchType", "read_boundary"]

#: Relative to the case root.
BOUNDARY_FILE = Path("constant") / "polyMesh" / "boundary"


class PatchType(StrEnum):
    """Patch types that constrain which boundary conditions are legal.

    Only the constrained ones are named. Everything else is an ordinary patch
    whose boundary condition is the user's choice, and inventing categories for
    those would imply rules that do not exist.
    """

    PATCH = "patch"
    """Unconstrained: any boundary condition may be used."""

    WALL = "wall"
    """A solid surface. Turbulence wall functions require this type, which is why
    the advisor (§6.9.1) needs it as well as the matrix."""

    EMPTY = "empty"
    """The front and back of a 2D case. **Must** carry the ``empty`` boundary
    condition on every field (E-C04) — a 2D case with a real condition there is
    silently solving a different problem."""

    SYMMETRY = "symmetry"
    SYMMETRY_PLANE = "symmetryPlane"
    WEDGE = "wedge"
    """Axisymmetric. Like ``empty``, its condition is dictated by the geometry."""

    CYCLIC = "cyclic"
    CYCLIC_AMI = "cyclicAMI"
    """Periodic, and paired: a cyclic patch is meaningless without its partner."""

    PROCESSOR = "processor"
    """Created by ``decomposePar``. Never shown to the user — it is an artefact of
    decomposition, not part of the case they wrote."""


#: Patch types whose boundary condition is fixed by the geometry, not chosen.
#: Offering alternatives here would be offering to break the case (E-C04).
CONSTRAINED: dict[str, str] = {
    PatchType.EMPTY: "empty",
    PatchType.SYMMETRY: "symmetry",
    PatchType.SYMMETRY_PLANE: "symmetryPlane",
    PatchType.WEDGE: "wedge",
    PatchType.CYCLIC: "cyclic",
    PatchType.CYCLIC_AMI: "cyclicAMI",
}


@dataclass(frozen=True, slots=True)
class Patch:
    """One entry from the boundary file."""

    name: str
    type: str
    n_faces: int = 0
    in_groups: tuple[str, ...] = ()

    @property
    def is_constrained(self) -> bool:
        """Whether the geometry dictates this patch's boundary condition."""
        return self.type in CONSTRAINED

    @property
    def required_condition(self) -> str | None:
        """The only legal boundary condition here, or ``None`` if free."""
        return CONSTRAINED.get(self.type)

    @property
    def is_internal(self) -> bool:
        """Whether this patch is decomposition machinery rather than the case."""
        return self.type == PatchType.PROCESSOR


def read_boundary(case: Path) -> list[Patch]:
    """Read the patches of a meshed case, in file order.

    Returns an empty list when the mesh has not been generated yet, which is the
    ordinary state of a freshly imported case — the matrix then says the mesh is
    needed rather than reporting an error the user cannot act on.

    ``processor*`` patches are excluded: they are created by ``decomposePar`` and
    are not part of the case the user wrote.
    """
    source = case / BOUNDARY_FILE
    if not source.is_file():
        return []

    document = Document.parse_bytes(source.read_bytes())
    body = _list_body(document)
    if body is None:
        return []

    try:
        interior = Document.parse(body)
    except ParseError:
        return []

    patches: list[Patch] = []
    for node in interior.root.children:
        if node.kind is not NodeKind.DICT or node.keyword is None:
            continue
        patch = Patch(
            name=node.keyword,
            type=interior.get(f"{node.keyword}/type") or "",
            n_faces=_as_int(interior.get(f"{node.keyword}/nFaces")),
            in_groups=_groups(interior.get(f"{node.keyword}/inGroups")),
        )
        if not patch.is_internal:
            patches.append(patch)
    return patches


def _list_body(document: Document) -> str | None:
    """Text inside the outermost counted list, without its parentheses."""
    for node in document.root.children:
        if node.kind is not NodeKind.OPAQUE:
            continue
        text = document.node_text(node).strip()
        if text.startswith("(") and text.endswith(")"):
            return text[1:-1]
    return None


def _as_int(value: str | None) -> int:
    try:
        return int(value) if value else 0
    except ValueError:
        return 0


def _groups(value: str | None) -> tuple[str, ...]:
    """Parse ``1(wall)`` — a counted list, inline this time."""
    if not value or "(" not in value:
        return ()
    inner = value[value.index("(") + 1 : value.rindex(")")]
    return tuple(inner.split())
